Controllers/Admin_CatalogController.cs
using Ecom_Food_Cart.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Data.SqlClient;
using System.Configuration;
using System.Data;

namespace Ecom_Food_Cart.Controllers
{
    public class Admin_CatalogController : Controller
    {
        ecom_databaseEntities ecom_DatabaseEntities;
        string cs = ConfigurationManager.ConnectionStrings["ConString"].ConnectionString;
        string cmd = string.Empty;

        // GET: Admin_Catalog
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult Categories()
        {
            List<tbl_categories> Category_List = new List<tbl_categories>();
            cmd = "ALLCATEGORYDATA";

            SqlConnection conn = new SqlConnection(cs);
            SqlCommand command = new SqlCommand(cmd, conn);
                       
            SqlDataAdapter sqlDataAdapter = new SqlDataAdapter(command);
            DataTable dt = new DataTable();

            sqlDataAdapter.Fill(dt);

            foreach(DataRow dr in dt.Rows)
            {
                Category_List.Add(new tbl_categories
                {
                    categoryId = Convert.ToInt32(dr["categoryId"]),
                    category_Name = dr["category_Name"].ToString(),
                    sort_Order = Convert.ToInt32(dr["sort_Order"])
                });
            }
            return View(Category_List);
        }

        public ActionResult AddCategories()
        {
            return View();
        }

       

        [HttpPost]
        public ActionResult AddCategories(tbl_categories tbl_Categories)
        {
           
            cmd = $"insert into tbl_category values (@Category_Name, @Sort_Order)";

            try
            {
                SqlConnection conn = new SqlConnection(cs);
                SqlCommand command = new SqlCommand(cmd, conn);

                command.Parameters.Add("@Category_Name", tbl_Categories.category_Name);
                command.Parameters.Add("@Sort_Order", tbl_Categories.sort_Order);


                conn.Open();
                command.ExecuteNonQuery();
                conn.Close();


                return Json(new { success = true });
            }
            catch (Exception ex)
            {

            }
            return RedirectToAction("Categories");
        }


        public ActionResult EditCategories(int id)
        {
            tbl_categories category = null;
            cmd = "GETCATEGORYBYID";

            SqlConnection conn = new SqlConnection(cs);
            SqlCommand command = new SqlCommand(cmd, conn);
            command.CommandType = CommandType.StoredProcedure;
            command.Parameters.AddWithValue("@categoryId", id);

            conn.Open();
            SqlDataReader reader = command.ExecuteReader();

            if (reader.Read())
            {
                category = new tbl_categories
                {
                    categoryId = Convert.ToInt32(reader["categoryId"]),
                    category_Name = reader["category_Name"].ToString(),
                    sort_Order = Convert.ToInt32(reader["sort_Order"])
                };
            }
            conn.Close();
            return View(category);
        }

        [HttpPost]
        public ActionResult UpdateCategory(tbl_categories category)
        {
            cmd = "UPDATECATEGORY";

            SqlConnection conn = new SqlConnection(cs);
            SqlCommand command = new SqlCommand(cmd, conn);

            command.CommandType = CommandType.StoredProcedure;
            command.Parameters.AddWithValue("@categoryId", category.categoryId);
            command.Parameters.AddWithValue("@category_Name", category.category_Name);
            command.Parameters.AddWithValue("@sort_Order", category.sort_Order);

            conn.Open() ;
            int i = command.ExecuteNonQuery();
            conn.Close();

            return RedirectToAction("Categories");
        }


        public ActionResult Products()
        {
            List<tbl_products> products = new List<tbl_products>();
            cmd = "ALLPRODUCTDATA";

            SqlConnection conn = new SqlConnection(cs);
            SqlCommand command = new SqlCommand(cmd, conn);

            SqlDataAdapter sqlDataAdapter = new SqlDataAdapter(command);
            DataTable dt = new DataTable();
            sqlDataAdapter.Fill(dt);

            foreach(DataRow dr in dt.Rows)
            {
                products.Add(new tbl_products
                {
                    category_Name = dr["category_Name"].ToString(),
                    product_Name = dr["product_Name"].ToString(),
                    price = Convert.ToDecimal(dr["price"]),
                    quantity = Convert.ToInt32(dr["quantity"])
                });
            }

            return View(products);
        }

        public ActionResult AddProducts()
        {
            List<tbl_categories> Category_List = new List<tbl_categories>();
            SqlConnection conn = new SqlConnection(cs);
            SqlCommand cmd = conn.CreateCommand();
            cmd.CommandText = "ALLCATEGORYDATA";

            SqlDataAdapter sqlDataAdapter = new SqlDataAdapter(cmd);
            DataTable dt = new DataTable();

            sqlDataAdapter.Fill(dt);

            foreach (DataRow dr in dt.Rows)
            {
                Category_List.Add(new tbl_categories
                {
                    categoryId = Convert.ToInt32(dr["categoryId"]),
                    category_Name = dr["category_Name"].ToString()
                });
            }

            ViewBag.categorylist = Category_List;

            return View();
        }

        
    }
}

Views/Admin_Catalog/AddCategories.cshtml
@model Ecom_Food_Cart.Models.tbl_categories
@{
    ViewBag.Title = "Add Categories";
    Layout = "~/Views/Shared/Admin_Layout.cshtml";
}

@using (Html.BeginForm("AddCategories", "Admin_Catalog", FormMethod.Post, new { id = "addCategoryForm" }))
{
    <!-- Content Wrapper. Contains page content -->
    <div class="content-wrapper">
        <!-- Content Header (Page header) -->
        <div class="content-header">
            <div class="container-fluid">
                <div class="row mb-2 ">
                    <div class="col-sm-6 row pl-3">
                        <div class="flex-column">
                            <h1 class="mr-3">Categories</h1>
                        </div>
                        <div class="col">
                            <ol class="breadcrumb float-sm-left ml-0">
                                <li class="breadcrumb-item"><a href=@Url.Action("Dashboard", "Admin_Dashboard")>Home</a></li>
                                <li class="breadcrumb-item active">Categories</li>
                            </ol>
                        </div>

                    </div><!-- /.col -->

                    <div class="col-sm-6">
                        <button type="button" class="btn btn-light float-sm-right mr-1" data-toggle="tooltip"
                                data-placement="top" title="Back">
                            <a href="@Url.Action("Categories","Admin_Catalog")" style="text-decorations:none; color:inherit; "><i class="fa fa-backward"></i></a>

                        </button>

                        <button type="submit" class="swalDefaultSuccess btn btn-success float-sm-right mr-1 " data-toggle="tooltip"
                                data-placement="top" title="Save">
                            <i class="fa fa-save"></i>
                        </button>
                        <button type="button" class="btn btn-success swalDefaultSuccess">
                            Launch Success Toast
                        </button>
                    </div><!-- /.col -->
                </div><!-- /.row -->
            </div><!-- /.container-fluid -->
        </div>
        <!-- /.content-header -->
        <!-- Main content -->
        <section class="content">
            <div class="container-fluid">


                <div class="col-12">

                    <div class="card">
                        <div class="card-header">
                            <h3 class="card-title">Add Category</h3>
                        </div>
                        <!-- /.card-header -->
                        <div class="card-body" style="padding-top: 0px;">


                            <div class="ml-3 mr-3">
                                <!-- Row-1 -->
                                <div class="form-row mt-3">
                                    <div class="col-md-3 text-left">
                                        <label for="category_Name" class="pr-5" style="font-weight: normal;">Category Name:</label>
                                    </div>
                                    <div class="col-md-9 ">
                                        @Html.TextBoxFor(e => e.category_Name, new { id = "category_Name", type = "text", @class = "form-control", placeholder = "Category Name", required = "required" })
                                    </div>
                                </div>

                                <!-- Row-1 -->
                                <div class="form-row mt-3">
                                    <div class="col-md-3 text-left">
                                        <label for="sort_Order" class="pr-5" style="font-weight: normal;">Sort Order:</label>
                                    </div>
                                    <div class="col-md-9 ">

                                        @Html.TextBoxFor(e => e.sort_Order, new { id = "sort_Order", type = "text", @class = "form-control", placeholder = "Sort Order", required = "required" })

                                    </div>
                                </div>

                            </div>


                        </div>
                    </div>
                </div>
            </div><!-- /.container-fluid -->
        </section>
        <!-- /.content -->
    </div>
    <!-- /.content-wrapper -->
}

@section AddCategories{
    <script>
        $(function() {
            $('#addCategoryForm').submit(function(event) {
                event.preventDefault();

                $.ajax({
                    url: this.action,
                    type: this.method,
                    data: $(this).serialize(),
                    success: function (response)
                    {
                        Swal.fire({
                            toast: true,
                            position: 'top-end',
                            icon: 'success',
                            title: 'Category added successfully!',
                            showConfirmButton: false,
                            timer: 3000
                        }).then(function() {
                            window.location.href = '@Url.Action("Categories", "Admin_Catalog")';
                        });
                    },
                    error: function(xhr, status, error) {
                        Swal.fire({
                            icon: 'error',
                            title: 'Error adding category',
                            text: error
                        });
                    }
                });
            });
        });
    </script>

}

Views/Admin_Catalog/AddProducts.cshtml
@model Ecom_Food_Cart.Models.tbl_products

@{
    ViewBag.Title = "Add Products";
    Layout = "~/Views/Shared/Admin_Layout.cshtml";
}


@using (Html.BeginForm("AddProducts", "Admin_Catalog", FormMethod.Post))
{
    <!-- Content Wrapper. Contains page content -->
    <div class="content-wrapper">
        <!-- Content Header (Page header) -->
        <div class="content-header">
            <div class="container-fluid">
                <div class="row mb-2 ">
                    <div class="col-sm-6 row pl-3">
                        <div class="flex-column">
                            <h1 class="mr-3">Products</h1>
                        </div>
                        <div class="col">
                            <ol class="breadcrumb float-sm-left ml-0">
                                <li class="breadcrumb-item"><a href=@Url.Action("Dashboard", "Admin_Dashboard")>Home</a></li>
                                <li class="breadcrumb-item active">Products</li>
                            </ol>
                        </div>

                    </div><!-- /.col -->
                    <div class="col-sm-6">
                        <a href="@Url.Action("Products", "Admin_Catalog")" style="text-decorations:none; color:inherit; ">
                            <button type="button" class="btn btn-light float-sm-right mr-1" data-toggle="tooltip"
                                    data-placement="top" title="Back">
                                <i class="fa fa-backward"></i>
                            </button>
                        </a>

                        <button type="submit" class="btn btn-success float-sm-right mr-1" data-toggle="tooltip"
                                data-placement="top" title="Save">
                            <i class="fa fa-save"></i>
                        </button>
                    </div><!-- /.col -->
                </div><!-- /.row -->
            </div><!-- /.container-fluid -->
        </div>
        <!-- /.content-header -->
        <!-- Main content -->
        <section class="content">
            <div class="container-fluid">


                <div class="col-12">

                    <div class="card">
                        <div class="card-header">
                            <h3 class="card-title">Add Product</h3>
                        </div>
                        <!-- /.card-header -->
                        <div class="card-body" style="padding-top: 0px;">
                            <div class="ml-3 mr-3">
                                <!-- Row-1 -->
                                <div class="form-row mt-3">
                                    <div class="col-md-3 text-left">
                                        <label for="Product_Name" class="pr-5" style="font-weight: normal;">Product Name:</label>
                                    </div>
                                    <div class="col-md-9 ">
                                        @Html.TextBoxFor(e => e.product_Name, new { @class = "form-control", id = "product_Name", placeholder = "Product Name", required = "required" })
                                        @*<input class="form-control" id="Product_Name" name="product_Name" placeholder="Product Name" required="required" type="text" value="">*@

                                    </div>
                                </div>
                                <!-- Row-2 -->
                                <div class="form-row mt-3">
                                    <div class="col-md-3 text-left">
                                        <label for="Category_Name" class="pr-5" style="font-weight: normal;">Category Name:</label>
                                    </div>
                                    <div class="col-md-9 ">
                                        @Html.DropDownListFor(e => e.categoryId, new SelectList(ViewBag.categorylist, "categoryId", "category_Name"),"--Select Category--", new { @class = "form-control", id = "product_Name", placeholder = "Product Name", required = "required" })
                                    </div>
                                </div>

                                <!-- Row-3 -->
                                <div class="form-row mt-3">
                                    <div class="col-md-3 text-left">
                                        <label for="Store_Name" class="pr-5" style="font-weight: normal;">Store Name:</label>
                                    </div>
                                    <div class="col-md-9 ">
                                        <input class="form-control" data-val="true" data-val-number="The field storeId must be a number." data-val-required="The storeId field is required." id="Store_Name" name="storeId" placeholder="Store Name" required="required" type="text" value="">

                                    </div>
                                </div>

                                <!-- Row-4 -->
                                <div class="form-row mt-3">
                                    <div class="col-md-3 text-left">
                                        <label for="Price" class="pr-5" style="font-weight: normal;">Price:</label>
                                    </div>
                                    <div class="col-md-9 ">
                                        @Html.TextBoxFor(model => model.price, new { @class = "form-control", id = "price",  placeholder = "Price", required = "required" })
                                    </div>
                                </div>

                                <!-- Row-5 -->
                                <div class="form-row mt-3">
                                    <div class="col-md-3 text-left">
                                        <label for="Quantity" class="pr-5" style="font-weight: normal;">Quantity:</label>
                                    </div>
                                    <div class="col-md-9 ">
                                        @Html.TextBoxFor(model => model.quantity, new { @class = "form-control", id = "quantity", placeholder = "Quantity", required = "required" })
                                    </div>
                                </div>

                                <!-- Row-6 -->
                                <div class="form-row mt-3">
                                    <div class="col-md-3 text-left">
                                        <label for="Description" class="pr-5" style="font-weight: normal;">Description:</label>
                                    </div>
                                    <div class="col-md-9 ">
                                        @Html.TextBoxFor(model => model.description, new { @class = "form-control", id = "description", placeholder = "Description", required = "required" })
                                    </div>
                                </div>
                                <!-- Row-7 -->
                                <div class="form-row mt-3">
                                    <div class="col-md-3 text-left">
                                        <label for="image" class="pr-5"
                                               style="font-weight: normal;">Image:</label>
                                    </div>
                                    <div class="col-md-9">
                                        <div class="mb-4 d-flex justify-content-start">
                                            <img id="selectedImage"
                                                 src="https://mdbootstrap.com/img/Photos/Others/placeholder.jpg"
                                                 alt="example placeholder" style="width: 200px;" />
                                        </div>
                                        <div class="d-flex justify-content-start">
                                            <div class="btn-xs btn-primary btn-rounded">
                                                <label class="form-label text-white m-1"
                                                       for="customFile1">
                                                    Choose
                                                    file
                                                </label>
                                                <input type="file" class="form-control d-none" id="customFile1"
                                                       onchange="displaySelectedImage(event, 'selectedImage')" />
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div><!-- /.container-fluid -->
        </section>
        <!-- /.content -->
    </div>
    <!-- /.content-wrapper -->
}

@section scriptaddprod{
    <script>
        function displaySelectedImage(event, elementId) {
            const selectedImage = document.getElementById(elementId);
            const fileInput = event.target;

            if (fileInput.files && fileInput.files[0]) {
                const reader = new FileReader();

                reader.onload = function (e) {
                    selectedImage.src = e.target.result;
                };

                reader.readAsDataURL(fileInput.files[0]);
            }
        }
    </script>
}

Views/Admin_Catalog/Categories.cshtml
@model IEnumerable<Ecom_Food_Cart.Models.tbl_categories>
@{
    ViewBag.Title = "Categories";
    Layout = "~/Views/Shared/Admin_Layout.cshtml";
}

<!-- Content Wrapper. Contains page content -->
<div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <div class="content-header">
        <div class="container-fluid">
            <div class="row mb-2 ">
                <div class="col-sm-6 row pl-3">
                    <div class="flex-column">
                        <h1 class="mr-3">Categories</h1>
                    </div>
                </div><!-- /.col -->
                <div class="col-sm-6">                    
                    <button type="button" class="btn btn-success float-sm-right mr-1" data-toggle="tooltip"
                            data-placement="top" title="Add New">
                        <a href="@Url.Action("AddCategories","Admin_Catalog")" style="text-decorations:none; color:inherit; "><i class="fa fa-plus"></i></a>
                    </button>                 

                </div><!-- /.col -->
            </div><!-- /.row -->
        </div><!-- /.container-fluid -->
    </div>
    <!-- /.content-header -->
    <!-- Main content -->
    <section class="content">
        <div class="container-fluid">
            <div class="col-12">

                <div class="card">
                    <div class="card-header">
                        <h3 class="card-title">Category List</h3>
                    </div>
                    <!-- /.card-header -->
                    <div class="card-body">
                        <table class="table table-bordered" id="categoryTable">
                            <thead>
                                <tr>
                                    <th>Category Name</th>
                                    <th>Sort Order</th>
                                    <th style="width: 40px">Actions</th>
                                </tr>
                            </thead>
                            <tbody>
                                @foreach (var items in Model)
                                {
                                    <tr>                                 
                                        <td>
                                            @Html.DisplayFor(modelItem => items.category_Name)
                                        </td>
                                        <td>@Html.DisplayFor(modelItem => items.sort_Order)</td>
                                        <td style="width: 13%">
                                            <a href=@Url.Action("EditCategories","Admin_Catalog",new {id = items.categoryId})>
                                                <button type="button" class="btn btn-primary float-sm-right mr-1" data-toggle="tooltip"
                                                        data-placement="top" title="Edit">
                                                    <i class="fas fa-pencil-alt"></i>
                                                </button>
                                            </a>
                                            

                                            <button type="button" class="btn btn-danger float-sm-right mr-1" data-toggle="tooltip"
                                                    data-placement="top" title="Delete">
                                                <i class="fa fa-trash"></i>
                                            </button>
                                        </td>
                                    </tr>
                                }
                            </tbody>
                        </table>
                    </div>
                    <!-- /.card-body -->
                    <div class="card-footer clearfix">
                        <ul class="pagination pagination-sm m-0 float-right">
                            <li class="page-item"><a class="page-link" href="#">«</a></li>
                            <li class="page-item"><a class="page-link" href="#">1</a></li>
                            <li class="page-item"><a class="page-link" href="#">2</a></li>
                            <li class="page-item"><a class="page-link" href="#">3</a></li>
                            <li class="page-item"><a class="page-link" href="#">»</a></li>
                        </ul>
                    </div>
                </div>
            </div>


        </div><!-- /.container-fluid -->
    </section>
    <!-- /.content -->
</div>
<!-- /.content-wrapper -->

Views/Admin_Catalog/EditCategories.cshtml
@model Ecom_Food_Cart.Models.tbl_categories
@{
    ViewBag.Title = "EditCategories";
    Layout = "~/Views/Shared/Admin_Layout.cshtml";
}

@using (Html.BeginForm("UpdateCategory", "Admin_Catalog", FormMethod.Post))
{
    <!-- Content Wrapper. Contains page content -->
    <div class="content-wrapper">
        <!-- Content Header (Page header) -->
        <div class="content-header">
            <div class="container-fluid">
                <div class="row mb-2 ">
                    <div class="col-sm-6 row pl-3">
                        <div class="flex-column">
                            <h1 class="mr-3">Categories</h1>
                        </div>
                    </div><!-- /.col -->

                    <div class="col-sm-6">
                        <button type="button" class="btn btn-light float-sm-right mr-1" data-toggle="tooltip"
                                data-placement="top" title="Back">
                            <a href="" style="text-decorations:none; color:inherit; "><i class="fa fa-backward"></i></a>

                        </button>
                        
                       
                        <button type="submit" class="btn btn-success float-sm-right mr-1" data-toggle="tooltip"
                                data-placement="top" title="Save">
                            <i class="fa fa-save"></i>
                        </button>
                        
                        
                    </div><!-- /.col -->
                </div><!-- /.row -->
            </div><!-- /.container-fluid -->
        </div>
        <!-- /.content-header -->
        <!-- Main content -->
        <section class="content">
            <div class="container-fluid">


                <div class="col-12">

                    <div class="card">
                        <div class="card-header">
                            <h3 class="card-title">Edit Category</h3>
                        </div>
                        <!-- /.card-header -->
                        <div class="card-body" style="padding-top: 0px;">
                            @Html.HiddenFor(e => e.categoryId)

                            <div class="ml-3 mr-3">
                                <!-- Row-1 -->
                                <div class="form-row mt-3">
                                    <div class="col-md-3 text-left">
                                        <label for="category_Name" class="pr-5" style="font-weight: normal;">Category Name:</label>
                                    </div>
                                    <div class="col-md-9 ">
                                        @Html.TextBoxFor(e => e.category_Name, new { id = "category_Name", type = "text", @class = "form-control", placeholder = "Category Name", required = "required" })
                                    </div>
                                </div>

                                <!-- Row-1 -->
                                <div class="form-row mt-3">
                                    <div class="col-md-3 text-left">
                                        <label for="sort_Order" class="pr-5" style="font-weight: normal;">Sort Order:</label>
                                    </div>
                                    <div class="col-md-9 ">

                                        @Html.TextBoxFor(e => e.sort_Order, new { id = "sort_Order", type = "text", @class = "form-control", placeholder = "Sort Order", required = "required" })

                                    </div>
                                </div>

                            </div>


                        </div>
                    </div>
                </div>
            </div><!-- /.container-fluid -->
        </section>
        <!-- /.content -->
    </div>
    <!-- /.content-wrapper -->
}